# Generated by Django 5.1.7 on 2025-03-12 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grupo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del producto')),
                ('descripcion', models.TextField(blank=True, max_length=500, null=True, verbose_name='Descripción del producto')),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio del producto')),
                ('stock', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Stock del producto')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado del producto')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='grupo.modelgrupo', verbose_name='Grupo del producto')),
                ('subgrupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='grupo.modelsubgrupo', verbose_name='Subgrupo del producto')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'producto',
            },
        ),
    ]
