
version: '3.8'

services:
  # Servicio de base de datos: PostgreSQL
  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: lmsuarez_admin
      POSTGRES_DB: foodsync_db
      POSTGRES_PASSWORD: edqnLMCSf31.
    ports:
      - 5432:5432
    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
    networks:
      - net-backend
  app:
    build:
      context: ../
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../:/app
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    ports:
      - 5000:5000
    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    #network_mode: service:db
    networks:
      - net-backend
    depends_on:
      - db

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

volumes:
  postgres-data:
# Use the `networks` key to enable the service to be on the same network as the database container.
networks:
  net-backend:
    driver: bridge
